export const knownSymptoms = [
    "fever",
    "persistent fatigue",
    "fatigue",
    "headache",
    "rash",
    "sore throat",
    "diarrhea",
    "vomiting",
    "nausea",
    "chills",
    "muscle aches",
    "dehydration",
    "abdominal cramps",
    "shortness of breath",
    "pneumonia",
    "respiratory failure",
    "chest tightness",
    "persistent cough",
    "wheezing",
    "difficulty breathing",
    "excessive thirst",
    "frequent urination",
    "weight loss",
    "blurred vision",
    "slow healing sores",
    "frequent infections",
    "severe headache",
    "chest pain",
    "dizziness",
    "lumps",
    "skin changes",
    "chronic pain",
    "chronic cough",
    "bowel changes",
    "bladder changes",
    "mucus",
    "chest discomfort",
    "low grade fever",
    "throbbing headache",
    "sensitivity to light",
    "sensitivity to sound",
    "aura",
    "vision disturbances",
    "watery diarrhea",
    "bloody diarrhea",
    "joint pain",
    "joint stiffness",
    "joint swelling",
    //"cough",
    "reduced range of motion"
];